spring:
  redis:
    ################### redis 单机版 start ##########################
    host: localhost
    port: 6379
    password:
    timeout: 6000
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 10
        # 连接池中的最大空闲连接 ，默认值也是8
        max-idle: 8
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 100
        # 连接池中的最小空闲连接 ，默认值也是0
        min-idle: 2
      shutdown-timeout: 100ms
  # sharding-jdbc 数据源配置
  shardingsphere:
    datasource:
      names: edas-admin
      edas-admin:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edas-admin?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: root
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: edas-admin
      default-database-strategy:
        none:
          any:
      default-table-strategy:
        none:
          any:
uaa:
  permit-all:
    - /login/usernamePasswordLogin
    - /login/validateCodeLogin
    - /login/thirdLogin
    - /validateCode/sendCode
    - /validateCode/sendSmsCode
    - /validateCode/sendEmailCode
    - /logout